---
- name: Check docker is installed
  command:
    cmd: docker --version
  register: docker_check
  changed_when: docker_check.rc != 0
  ignore_errors: yes

- name: Install software
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    state: present
    update_cache: yes
  when: docker_check is changed
  become: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: docker_check is changed
  become: yes

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
    state: present
    update_cache: yes
  when: docker_check is changed
  become: yes

- name: Install Docker
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present
    update_cache: yes
  when: docker_check is changed
  become: yes

- name: Check docker-compose is installed
  command: docker-compose --version
  register: docker_compose_check
  changed_when: docker_compose_check.rc != 0
  ignore_errors: yes

# Requires pipx. Available in pipx.yml
- name: Install docker-compose
  shell:
    cmd: "{{ system_python3_dir }} -m pipx install docker-compose"
  when: docker_compose_check is changed

