- name: Install snapd
  apt:
    name: snapd
    state: present
    update_cache: yes
  become: yes

- name: Delete Pycharm CE
  shell:
    cmd: "{{ system_snap_dir }} remove --purge pycharm-community"
  when: snapd_pycharm_state == "absent"
  become: yes

- name: Install Pycharm CE
  shell:
    cmd: "{{ system_snap_dir }} install pycharm-community --classic"
  when: snapd_pycharm_state == "present"
  become: yes
